spring.application.name=ApiGateway
server.port=9001

# Eureka
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Route user-service (priorité 1)
spring.cloud.gateway.routes[0].id=smartride-user-service
spring.cloud.gateway.routes[0].uri=lb://smartride-user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**
spring.cloud.gateway.routes[0].order=1

# Route trajet-service (priorité 2)
spring.cloud.gateway.routes[1].id=smartride-trajet-service
spring.cloud.gateway.routes[1].uri=lb://smartride-trajet-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/trajets/**
spring.cloud.gateway.routes[1].order=2

# Route job (priorité 3)
spring.cloud.gateway.routes[2].id=job
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/jobs/**
spring.cloud.gateway.routes[2].order=3

# Disable config server
spring.cloud.config.enabled=false


# Route rating-service (priorité 4)
spring.cloud.gateway.routes[3].id=rating-service
spring.cloud.gateway.routes[3].uri=lb://RATING-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/ratings/**
spring.cloud.gateway.routes[3].order=4
