-- Seed drivers for the in-memory H2 schema generated by Hibernate (create-drop).
-- driver1@smartride.tn matches the Keycloak CHAUFFEUR account so the frontend can
-- resolve the logged-in chauffeur to a numeric driver id.
INSERT INTO drivers (nom, prenom, email, telephone, statut, marque_vehicule, modele_vehicule, plaque_immatriculation, user_id) VALUES
  ('One',     'Driver',  'driver1@smartride.tn',     '+216 90 000 001', 'DISPONIBLE', 'Toyota',   'Yaris 2023',    'TN 999 RIDE', 2),
  ('Benali',  'Mohamed', 'm.benali@smartride.com',   '+216 91 234 567', 'DISPONIBLE', 'Toyota',   'Corolla 2023',  'TN 123 ABC',  NULL),
  ('Amara',   'Fatima',  'f.amara@smartride.com',    '+216 92 345 678', 'HORS_LIGNE', 'BMW',      '320i 2022',     'TN 456 XYZ',  NULL);
